"""
Domain models for the Fathom financing options analyzer.

Defines all input, output, and intermediate data types used by the
calculation engine. All monetary values use Decimal to avoid floating-point
precision errors.
"""

from decimal import Decimal
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class OptionType(Enum):
    """
    Financing option types supported by the engine.

    Each type has distinct required fields on FinancingOption.
    """

    CASH = "cash"
    TRADITIONAL_LOAN = "traditional_loan"
    PROMO_ZERO_PERCENT = "promo_zero_percent"
    PROMO_CASH_BACK = "promo_cash_back"
    PROMO_PRICE_REDUCTION = "promo_price_reduction"
    CUSTOM = "custom"


class CaveatType(Enum):
    """
    Types of risk caveats the engine can generate.

    Each caveat type corresponds to a specific financial risk pattern.
    """

    DEFERRED_INTEREST_RISK = "deferred_interest_risk"
    OPPORTUNITY_COST_DOMINANCE = "opportunity_cost_dominance"
    HIGH_INTEREST_TOTAL = "high_interest_total"


class Severity(Enum):
    """
    Severity levels for caveats.

    Used to prioritize which caveats are most important to the user.
    """

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class FinancingOption(BaseModel):
    """
    A single financing option to compare.

    Uses a flat structure with optional fields rather than a class hierarchy.
    Required fields depend on option_type:

    - CASH: only purchase_price required
    - TRADITIONAL_LOAN: apr, term_months required; down_payment optional
    - PROMO_ZERO_PERCENT: term_months, post_promo_apr required;
      deferred_interest, retroactive_interest, down_payment optional
    - PROMO_CASH_BACK: apr, term_months, cash_back_amount required;
      down_payment optional
    - PROMO_PRICE_REDUCTION: apr, term_months, discounted_price required;
      down_payment optional
    - CUSTOM: apr, term_months required; all optional fields accepted
    """

    option_type: OptionType
    label: str
    purchase_price: Decimal
    apr: Decimal | None = None
    term_months: int | None = None
    down_payment: Decimal | None = None
    post_promo_apr: Decimal | None = None
    deferred_interest: bool = False
    retroactive_interest: bool = True
    cash_back_amount: Decimal | None = None
    discounted_price: Decimal | None = None


class GlobalSettings(BaseModel):
    """
    Global comparison settings that apply to all options.

    Controls opportunity cost modeling, inflation adjustment, and tax savings.
    """

    return_rate: Decimal
    inflation_enabled: bool = False
    inflation_rate: Decimal = Field(default_factory=lambda: Decimal(0))
    tax_enabled: bool = False
    tax_rate: Decimal = Field(default_factory=lambda: Decimal(0))


class MonthlyDataPoint(BaseModel):
    """
    Data for a single month in the amortization/cost schedule.

    Provides the granular data needed for chart rendering in Phase 3.
    """

    model_config = ConfigDict(frozen=True)

    month: int
    payment: Decimal
    interest_portion: Decimal
    principal_portion: Decimal
    remaining_balance: Decimal
    investment_balance: Decimal
    cumulative_cost: Decimal
    opportunity_cost: Decimal = Field(default_factory=lambda: Decimal(0))
    inflation_adjustment: Decimal = Field(default_factory=lambda: Decimal(0))
    tax_savings: Decimal = Field(default_factory=lambda: Decimal(0))


class OptionResult(BaseModel):
    """
    Computed result for a single financing option.

    Contains the breakdown of all cost components that sum to the
    True Total Cost.
    """

    model_config = ConfigDict(frozen=True)

    total_payments: Decimal
    total_interest: Decimal
    opportunity_cost: Decimal
    tax_savings: Decimal
    inflation_adjustment: Decimal
    rebates: Decimal
    true_total_cost: Decimal
    monthly_data: list[MonthlyDataPoint]


class PromoResult(BaseModel):
    """
    Dual-outcome result for promotional financing options.

    Models both the disciplined scenario (paid off in time) and the
    penalty scenario (not paid off before promo expires).
    """

    model_config = ConfigDict(frozen=True)

    paid_on_time: OptionResult
    not_paid_on_time: OptionResult
    required_monthly_payment: Decimal
    break_even_month: int


class Caveat(BaseModel):
    """
    A risk caveat generated by the analysis engine.

    Provides structured warnings about financial risks associated with
    specific options or the overall comparison.
    """

    model_config = ConfigDict(frozen=True)

    caveat_type: CaveatType
    message: str
    severity: Severity


class ComparisonResult(BaseModel):
    """
    Complete result of comparing multiple financing options.

    Contains per-option results, the normalized comparison period, and
    any generated caveats.
    """

    model_config = ConfigDict(frozen=True)

    results: dict[str, OptionResult | PromoResult]
    comparison_period_months: int
    caveats: list[Caveat]
